### ISSUE TITLE
When already up-to-date common-mikrotik-routers fails to continue

### ISSUE THREAD

**Issue by turnrye** [HamWAN/infrastructure-configs#4]
```
TASK: [common-mikrotik-routers | Upgrade routeros] ****************************
<r1.leb.memhamwan.net> ESTABLISH CONNECTION FOR USER: memhamwan on PORT 22 TO r1.leb.memhamwan.net
<r1.leb.memhamwan.net> EXEC /system package update upgrade
No handlers could be found for logger "paramiko.transport"
```

I think this is due to /system package update upgrade returning just a newline; no text.

**Comment by turnrye** [comment]
I was kind of close... here's what happens on that router when that executes:
[admin@r1.leb] > /system package update upgrade 
  current-version: 6.30
   latest-version: 6.30
           status: System is already up to date
-- [Q quit|D dump|C-z continue]

So it never returns a prompt... looking at http://docs.ansible.com/raw_module.html, which this task is using, since this doesnt return, the task never completes.

**Comment by cjeannerot** [comment]
I have the same problem on CentOS 7 

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [Mise en place de la QOS sur les MT] **************************************

TASK [DNS] *********************************************************************
task path: /etc/ansible/test.yml:9
<172.23.2.254> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO 172.23.2.254
<172.23.2.254> EXEC /exit
No handlers could be found for logger "paramiko.transport"

**Comment by bkus** [comment]
Won't fix.  Prefer to rewrite with routeros API module.
